spring:
  profiles:
    active: local # 기본적으로 local이 선택된다는 뜻
    multipart:
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
  mail:
    host: smtp.gmail.com
    port: 587
    username: parkbk1908@gmail.com
    password: lvzqgkkpzvqzcckl
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp
  datasource:
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    url: jdbc:log4jdbc:mysql://175.121.103.209:3306/lfcFan?useUnicode=true&characterEncoding=utf8&autoReconnect=true&serverTimezone=Asia/Seoul&useOldAliasMetadataBehavior=true&zeroDateTimeNehavior=convertToNull
    username: sbsst
    password: sbs123414
mybatis:
  type-aliases-package: com.example.lfcFan.dto
server:
  error:
    include-exception: true
    include-stacktrace: always
    include-message: always
    include-binding-errors: always
custom:
  genFileDirPath: /usr/lfcFan-img
  siteName: LiverpoolFanPage
  siteUrl: http://localhost:8085
  siteMainUri: http://localhost:8085/usr/article/home
  siteLoginUri: http://localhost:8085/usr/member/login
  emailFrom: no-reply@localhost
  emailFromName: LiverpoolFanPage
  logging:
    dir: log
    level: info

---

spring:
  profiles: local
server:
  port: 8085